version: "3.9"

services:
  db:
    image: postgres:15
    container_name: flashdecks-db
    environment:
      POSTGRES_DB: flashdecks
      POSTGRES_USER: flashdecks
      POSTGRES_PASSWORD: flashdecks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flashdecks"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
    container_name: flashdecks-backend
    env_file:
      - ../backend/.env.example
    environment:
      DATABASE_URL: postgresql+psycopg2://flashdecks:flashdecks@db:5432/flashdecks
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend/app:/app/app:ro
    command: ["sh", "-c", "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build:
      context: ../frontend
      args:
        - VITE_API_BASE_URL=http://backend:8000/api/v1
    container_name: flashdecks-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
