import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { ArrowRightIcon, BoltIcon, ChartBarIcon, ClockIcon } from "@heroicons/react/24/outline";
import { ThemeToggle } from "@/components/navigation/ThemeToggle";
export const LandingPage = () => {
    return (_jsxs("div", { className: "min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-100 dark:from-slate-950 dark:via-slate-950 dark:to-slate-900", children: [_jsx("header", { className: "relative z-20", children: _jsxs("nav", { className: "mx-auto flex max-w-6xl items-center justify-between px-6 py-6", children: [_jsxs(Link, { to: "/", className: "flex items-center gap-2 text-lg font-semibold", children: [_jsx("span", { className: "flex size-9 items-center justify-center rounded-xl bg-brand-500 text-white shadow-lg shadow-brand-500/30", children: "FD" }), _jsx("span", { className: "tracking-tight text-slate-900 dark:text-slate-50", children: "Flash-Decks" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [_jsx(ThemeToggle, {}), _jsx(Link, { to: "/login", className: "rounded-full border border-slate-200 px-4 py-2 text-sm font-medium text-slate-600 transition hover:border-brand-500 hover:text-brand-600 dark:border-slate-700 dark:text-slate-300 dark:hover:border-brand-400 dark:hover:text-brand-300", children: "Log in" }), _jsx(Link, { to: "/signup", className: "rounded-full bg-brand-500 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-brand-500/30 transition hover:bg-brand-600", children: "Sign up" })] })] }) }), _jsxs("main", { className: "isolate mx-auto flex max-w-6xl flex-col gap-24 px-6 pb-24 pt-10", children: [_jsxs("section", { className: "grid gap-12 lg:grid-cols-[1.3fr,1fr] lg:items-center", children: [_jsxs("div", { className: "space-y-8", children: [_jsx("span", { className: "inline-flex items-center gap-2 rounded-full bg-white/70 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-brand-600 shadow-card shadow-brand-500/10 ring-1 ring-brand-500/20 dark:bg-slate-900/70 dark:text-brand-300", children: "Spaced repetition done right" }), _jsx("h1", { className: "text-4xl font-bold leading-tight text-slate-900 sm:text-5xl dark:text-slate-50", children: "Retain more. Study smarter. Fall in love with learning again." }), _jsx("p", { className: "max-w-xl text-lg text-slate-600 dark:text-slate-300", children: "Flash-Decks combines adaptive scheduling, handcrafted decks, and beautiful analytics to keep you on track. Master anything with guided reviews, practice drills, and exam simulations." }), _jsxs("div", { className: "flex flex-wrap items-center gap-4", children: [_jsxs(Link, { to: "/signup", className: "flex items-center gap-2 rounded-full bg-brand-500 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-brand-500/30 transition hover:bg-brand-600", children: ["Start learning free ", _jsx(ArrowRightIcon, { className: "size-4" })] }), _jsxs("a", { href: "#features", className: "flex items-center gap-2 text-sm font-semibold text-slate-700 transition hover:text-brand-600 dark:text-slate-200 dark:hover:text-brand-300", children: ["Explore the platform ", _jsx(ArrowRightIcon, { className: "size-4" })] })] }), _jsx("dl", { className: "grid grid-cols-2 gap-6 sm:grid-cols-4", children: [
                                            { label: "Decks", value: "200+" },
                                            { label: "Active learners", value: "12k" },
                                            { label: "Avg. retention", value: "93%" },
                                            { label: "Daily cards reviewed", value: "65k" }
                                        ].map((stat) => (_jsxs("div", { className: "rounded-2xl bg-white/60 p-4 shadow-card shadow-brand-500/10 dark:bg-slate-900/60", children: [_jsx("dt", { className: "text-xs uppercase tracking-wide text-slate-500 dark:text-slate-400", children: stat.label }), _jsx("dd", { className: "mt-2 text-xl font-semibold text-slate-900 dark:text-white", children: stat.value })] }, stat.label))) })] }), _jsx("div", { className: "relative flex", children: _jsxs("div", { className: "relative w-full overflow-hidden rounded-3xl bg-slate-900 text-white shadow-2xl shadow-brand-500/20", children: [_jsx("div", { className: "absolute -top-20 -left-16 size-40 rounded-full bg-brand-500/30 blur-3xl", "aria-hidden": true }), _jsx("div", { className: "absolute -bottom-24 -right-10 size-48 rounded-full bg-sky-400/20 blur-3xl", "aria-hidden": true }), _jsxs("div", { className: "space-y-4 p-8", children: [_jsxs("div", { className: "glass-panel flex items-center justify-between rounded-2xl px-4 py-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs text-slate-300", children: "Due today" }), _jsx("p", { className: "text-2xl font-bold text-white", children: "32 cards" })] }), _jsx("span", { className: "rounded-full bg-brand-500/20 px-3 py-1 text-xs font-semibold text-brand-200", children: "+12%" })] }), _jsxs("div", { className: "glass-panel rounded-2xl p-4", children: [_jsx("p", { className: "text-sm text-slate-300", children: "Daily streak" }), _jsx("p", { className: "text-3xl font-bold text-white", children: "42 days" }), _jsx("div", { className: "mt-3 h-2 rounded-full bg-slate-800", children: _jsx("div", { className: "h-2 rounded-full bg-gradient-to-r from-brand-400 to-sky-400", style: { width: "78%" } }) })] }), _jsx("div", { className: "space-y-3 rounded-2xl bg-white/10 p-4", children: [
                                                        { deck: "Advanced Biology", progress: 68 },
                                                        { deck: "Spanish Essentials", progress: 84 },
                                                        { deck: "Algorithms", progress: 45 }
                                                    ].map((item) => (_jsxs("div", { className: "rounded-xl bg-white/5 p-3", children: [_jsxs("div", { className: "flex items-center justify-between text-sm font-medium text-white", children: [_jsx("span", { children: item.deck }), _jsxs("span", { children: [item.progress, "%"] })] }), _jsx("div", { className: "mt-2 h-1.5 rounded-full bg-white/10", children: _jsx("div", { className: "h-1.5 rounded-full bg-gradient-to-r from-brand-400 to-sky-400", style: { width: `${item.progress}%` } }) })] }, item.deck))) })] })] }) })] }), _jsx("section", { id: "features", className: "grid gap-8 lg:grid-cols-3", children: [
                            {
                                icon: BoltIcon,
                                title: "Adaptive reviews",
                                body: "An SM-2 inspired scheduler keeps the right cards at your fingertips and powers personalized pacing."
                            },
                            {
                                icon: ChartBarIcon,
                                title: "Rich analytics",
                                body: "Understand your streaks, strengths, and blind spots with dashboards designed to boost motivation."
                            },
                            {
                                icon: ClockIcon,
                                title: "Flexible study modes",
                                body: "Switch between review, practice, and timed exam prep in seconds and sync across any device."
                            }
                        ].map((feature) => (_jsxs("div", { className: "group rounded-3xl bg-white/80 p-6 shadow-card shadow-brand-500/10 transition hover:-translate-y-1 hover:shadow-brand-500/20 dark:bg-slate-900/70", children: [_jsx(feature.icon, { className: "size-10 rounded-xl bg-brand-500/10 p-2 text-brand-500 transition group-hover:bg-brand-500 group-hover:text-white" }), _jsx("h3", { className: "mt-6 text-xl font-semibold text-slate-900 dark:text-slate-50", children: feature.title }), _jsx("p", { className: "mt-3 text-sm text-slate-600 dark:text-slate-300", children: feature.body })] }, feature.title))) })] }), _jsx("footer", { className: "border-t border-slate-200/60 bg-white/60 py-12 text-sm text-slate-500 dark:border-slate-800 dark:bg-slate-950/80 dark:text-slate-400", children: _jsxs("div", { className: "mx-auto flex max-w-6xl flex-col items-center justify-between gap-6 px-6 md:flex-row", children: [_jsxs("p", { children: ["\u00A9 ", new Date().getFullYear(), " Flash-Decks. Stay curious."] }), _jsxs("div", { className: "flex gap-4", children: [_jsx(Link, { to: "/login", className: "hover:text-brand-600 dark:hover:text-brand-300", children: "Log in" }), _jsx(Link, { to: "/signup", className: "hover:text-brand-600 dark:hover:text-brand-300", children: "Sign up" })] })] }) })] }));
};
